naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      img: https://openapi.naver.com/v1/search/image
  client:
    id: LTuEgPOrgG5iv1jHszqO
    secret: GvBuAPq6Zy

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher